=== sleepy-earth-9049 Config Vars
DATABASE_URL:               postgres://ocwcpwkzqhyanf:HDLlZ4Vmi_ujZJBYHDCmGhu9mh@ec2-54-197-241-67.compute-1.amazonaws.com:5432/d1el4m1q0m99q9
HEROKU_POSTGRESQL_BLUE_URL: postgres://ocwcpwkzqhyanf:HDLlZ4Vmi_ujZJBYHDCmGhu9mh@ec2-54-197-241-67.compute-1.amazonaws.com:5432/d1el4m1q0m99q9
LANG:                       en_US.UTF-8
RACK_ENV:                   production
RAILS_ENV:                  production
SECRET_KEY_BASE:            4c207752b123065969095e9fa1589e3120f0147cf19ce78926537b8e3853cc6d1ca306f23cd9d6e68e7dce0ec87be68556975d8618990f67e6364181c6a2a0e8